version: "2.1"
services:
 rabbit:
  image: rabbitmq:3-management
  container_name: rabbitmq
  ports:
    - "35672:15672"
    - "25672:5672"
  networks:
    default:
 Chat:
  build: ./chatap
  image: chatserver
  container_name: ChatServer
  networks:
   default:
networks:
 default:
  driver: bridge
  enable_ipv6: false
  ipam:
   driver: default
   config:
    - subnet: 172.50.0.1/24
      gateway: 172.50.0.1
